version: "3.1"
services:

  billing-server:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./:/var/www
      - ./app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:8020:8000"
    networks:
      - backend
      - async-arch-external

  billing-app:
    build: .
    working_dir: /var/www
    environment:
      - TERM=xterm-256color
    volumes:
      - ./:/var/www
    networks:
      - backend
      - async-arch-external

  billing-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5420:5432"
    networks:
      - backend

volumes:
  db-data:
    driver: local
  cache-data:
    driver: local

networks:
  backend:
    driver: bridge

  async-arch-external:
    external:
      name: async-arch-external
